version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "05:43"
  open-pull-requests-limit: 50
  target-branch: main
  labels:
  - dependency_updates
  ignore:
  - dependency-name: "bokeh"
    versions: [ ">=3" ]
  groups:
    python-dependencies:
      applies-to: version-updates
      dependency-type: production
    python-dependencies-dev:
      applies-to: version-updates
      dependency-type: development
    python-dependencies-security:
      applies-to: security-updates
      dependency-type: production
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "05:33"
  target-branch: main
  labels:
  - CI
  groups:
    github-actions:
      applies-to: version-updates
      dependency-type: production
