version: 2
updates:
- package-ecosystem: uv
  directory: "/"
  schedule:
    interval: monthly
    day: tuesday
    time: "06:43"
  target-branch: main
  labels:
  - dependency_updates
  versioning-strategy: "increase-if-necessary"
  open-pull-requests-limit: 30
  groups:
    python-production:
      applies-to: version-updates
      dependency-type: production
      update-types:
        - minor
        - patch
    python-development:
      applies-to: version-updates
      dependency-type: development
      update-types:
        - major
        - minor
        - patch
  ignore:
    - dependency-name: "bokeh"
      versions: [ ">=3" ]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    day: monday
    interval: monthly
    time: "05:33"
  target-branch: main
  labels:
  - dependency_updates
  groups:
    github-actions:
      applies-to: version-updates
      dependency-type: production
