version: 2

formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - cli

mkdocs:
  configuration: ./mkdocs.yml
  fail_on_warning: false
